In [1]:
num_head = 9
emb_dim = 512
from torch.functional import F
import torch

inputs = [0.1, -torch.inf, -torch.inf]
inputs = torch.tensor(inputs, device="cuda")
res = F.softmax(inputs, dim=-1)
print(res)

tensor([1., 0., 0.], device='cuda:0')


In [6]:
def _safe_mask(invalid_mask):
    valid = ~invalid_mask                                      # [B, N] True=valid
    all_invalid = ~valid.any(dim=-1, keepdim=True) 
    print(all_invalid)             # [B, 1] True when whole row is padding
    return valid | all_invalid                                  # unmask full row for all-padding elements


invalid_mask = torch.tensor([[True, True, True], [False, True, True]], device="cuda")
print(invalid_mask.shape)
print(_safe_mask(invalid_mask))

torch.Size([2, 3])
tensor([[ True],
        [False]], device='cuda:0')
tensor([[ True,  True,  True],
        [ True, False, False]], device='cuda:0')
